# Generated by Django 3.1.4 on 2020-12-17 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomBaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('custombasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='dataView.custombasemodel')),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            bases=('dataView.custombasemodel',),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('custombasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='dataView.custombasemodel')),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            bases=('dataView.custombasemodel',),
        ),
        migrations.CreateModel(
            name='DiscountBand',
            fields=[
                ('custombasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='dataView.custombasemodel')),
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            bases=('dataView.custombasemodel',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('custombasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='dataView.custombasemodel')),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('manufacturing_cost', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            bases=('dataView.custombasemodel',),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sale', models.DecimalField(decimal_places=2, max_digits=20)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cogs', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataView.country')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataView.department')),
                ('discount_band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataView.discountband')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataView.product')),
            ],
        ),
    ]
